spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/springboot_sell?characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://192.168.30.113/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: 139.199.21.227
    port: 6379
server:
  context-path: /sell
  port: 8080
logging:
  pattern:
    console: "%d - %msg%n"
